### ISSUE TITLE
Which WordNet Release is this made from?

### ISSUE THREAD

**Issue by YamiPryncess** [fluhus/wordnet-to-json#3]
You wrote that it's from 2010 but the 3.1 version is actually from 2011. The 3.0 version happened years before that I believe. So is this the 3.1 version or the 3.0?

Thanks for the resource!

**Comment by fluhus** [comment]
Hi,

I'm happy that it's useful for you!

The resource is based on version 3.1 of the data. I can add that to the README.
Are you referring to the 2010 in the citation in the README? If so, then it's a part of the citation (taken from their [website](https://wordnet.princeton.edu/citing-wordnet)).

**Comment by fluhus** [comment]
Submitted https://github.com/fluhus/wordnet-to-json/commit/f6c83faf1680edf4e5bcd39c6c6a8d1438c87596.

**Comment by YamiPryncess** [comment]
And none of the data is altered in any way? :) Some one else made a open source JSON dictionary of WordNet but they heavily altered it. Not sure in what ways. It's nice to have both the original and improvements easily accessible!

**Comment by fluhus** [comment]
What kind of alteration did they do?
I can double check my code to make sure :)

This data dump is supposed to represent the original dataset as accurately as possible, so no (intentional) alteration was done. The code that generates it is [here](https://github.com/fluhus/gostuff/blob/master/nlp/wordnet/parser.go).

**Comment by fluhus** [comment]
Can I close this issue?
Let me know if you need more information.

**Comment by YamiPryncess** [comment]
I do have one more question actually. Sorry I'm still paying attention to this thread. I just couldn't reply at the time.

So can WordNet find all conjugations of a word? I'm going to start learning how to use it right now.

**Comment by fluhus** [comment]
As far as I remember WordNet doesn't have conjugations.
Consider this [search for the word **go**](http://wordnetweb.princeton.edu/perl/webwn?c=8&s=go); I searched the result page itself for **went** and **gone** and could only find them in the examples, but not explicitly isolated in any field.

You can experiment with the web UI to get a sense of what kind of information WN has to offer. The JSON dump in this repository should have everything that's on the web UI (happy to know if not 😃).

HTH
